### ISSUE TITLE
rspec-retry not compatible with RSpec 3.3

### ISSUE THREAD

**Issue by JonRowe** [y310/rspec-retry#25]
In RSpec 3.3 we modified our private api for storing memoized variables (lets and subject), the monkey patch you're using is now incompatible see rspec/rspec-core#1999

**Comment by myronmarston** [comment]
In general, we prefer if extensions limit themselves to our public APIs, as that prevents this kind of issue.  What kind of public APIs would you want to no longer have to monkey patch RSpec?

**Comment by galulex** [comment]
[lib/rspec_ext/rspec_ext.rb#L15](https://github.com/y310/rspec-retry/blob/master/lib/rspec_ext/rspec_ext.rb#L15)

**Comment by JonRowe** [comment]
We're aware of what you currently (incorrectly) do to override our private APIs, I feel you would to better to retry examples without keeping existing instances around...

**Comment by karlingen** [comment]
:+1:

**Comment by fabn** [comment]
Works like a charm, @y310 can you merge this and release? Thanks

**Comment by michaelglass** [comment]
@JonRowe suggestion for where to wrap tests for retries?

**Comment by michaelglass** [comment]
closing for #35
