### ISSUE TITLE
Invoking database cleaner between retries

### ISSUE THREAD

**Issue by swaroopmurthy** [y310/rspec-retry#29]
We have a flaky test suite of >2500 tests that invokes [DatabaseCleaner](https://github.com/DatabaseCleaner/database_cleaner) between tests. Despite having a retry count of 3, we're seeing issues like unique constraint violated and record already exists...

Is there a way to explicitly invoke DatabaseCleaner between each retry attempt?

**Comment by michaelglass** [comment]
there is no current api exposed for this functionality, see #33 if you want to add it!

**Comment by tye** [comment]
If you put DatabaseCleaner in before/after hooks instead of an around hook then your db will get cleaned between retries.

My rspec config looks something like this:

```ruby
config.before(:each) do |example|
  DatabaseCleaner.start
end

config.after(:each) do |example|
  Capybara.reset_sessions! if example.metadata[:js]
  DatabaseCleaner.clean
end

config.around(:each) do |example|
  if example.metadata[:js]
    example.run_with_retry retry: 3
  else
    example.run
  end
end
```

If you're using Capybara you will need to call Capybara.reset_sessions! before cleaning the database in the after hook.

**Comment by michaelglass** [comment]
@abrom just added between retry hooks, too (#50)

**Comment by joao-esteves** [comment]
Came across this and it should be helpful to leave my findings.

Unlike what's said above, `DatabaseCleaner.cleaning do` inside an `around` hook is cleaning the database between retries as of now. It was something else polluting my DB.

Check your `retry_callback`. In my case, I was printing a variable from a macro for debugging. It is an ActiveRecord object with FactoryGirl. The thing is that DatabaseCleaner was removing it from the DB before this method, so by printing the variable I was rerunning the macro and reinserting it in the DB with no `DatabaseCleaner.cleaning` block to remove it.
