### ISSUE TITLE
Features for a "randomly passing" mindset?

### ISSUE THREAD

**Issue by maxlinc** [y310/rspec-retry#4]
I like this project, but I don't want to simply retry and forget flaky tests.
I like the philosophy from [No more flaky tests on the Go team](http://www.thoughtworks-studios.com/blog/no-more-flaky-tests-go-team) - I think of them as "randomly passing", not "randomly failing".

[Continuous Integration at Google Scale (PDF)](http://www.eclipsecon.org/2013/sites/eclipsecon.org.2013/files/Continuous%20Integration%20at%20Google%20Scale.pdf) also has a clear plan:

>Solutions (Google does all of these):
* Fix them!!!
  * Difficult - requires developer time
* Hide them
  * Retry causing delays 
  * Identify infrastructure flakes
  * Use metrics to ignore
* Track them
  * Provide metrics to prioritize fix / hide

Currently rspec retry only does "retry - causing delays".  It'd be good add some other features that would support this.

Some possible examples:

A summary report: which tests were retried?  How many times?
Exporting/Importing metrics from previous runs: did a test become flaky that was stable in the past?
Automatic quarantine: run stable tests first and make sure they succeed.  Run tests known to be flaky only if the stable tests pass.

**Comment by michaelglass** [comment]
this stinks of feature creep. Happy for what you're talking about to be a related gem and happy to expose APIs to help support functionality but that functionality shouldn't live in rspec-retry
